### ISSUE TITLE
Clustering add-on tool error

### ISSUE THREAD

**Issue by cambriausa03** [seeq12/seeq-clustering#6] opened 2022-05-19 15:26 UTC
SPyRuntimeError                           Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/seeq/addons/clustering/app/clusterApp/main.py in uiClusterSupervised(*args)
    397                         print('SELECTION ERROR. Please make a selection with the lasso tool first.')
    398                         return
--> 399 		clusterSupervised(
    400                         app, buttons, xsignal, ysignal, clusterExtent,
    401                         datadf, indexofselection, hist_grid_points,

~/.local/lib/python3.8/site-packages/seeq/addons/clustering/app/clusterApp/ui.py in clusterSupervised(app, buttons, xsignal, ysignal, clusterExtent, datadf, indexofselection, hist_grid_points, basename, timeOfRun, closeButton)
    237     app.extent_scalar = float(clusterExtent.value) #for cluster extent looks at self.extent_scalar
    238 
--> 239     _wrapUp(app, checksum, basename, timeOfRun, closeButton)
    240     return
    241 

~/.local/lib/python3.8/site-packages/seeq/addons/clustering/app/clusterApp/ui.py in _wrapUp(app, checksum, basename, timeOfRun, closeButton)
     85     print("\rPushing Conditions...")
     86     clear()
---> 87     app.push_cluster_formulas(checksum, basename, timeOfRun)
     88     print("\rOrganizing Worksheet...")
     89 

~/.local/lib/python3.8/site-packages/seeq/addons/clustering/app/clusterApp/main.py in push_cluster_formulas(self, checksum, basename, timeOfRun)
    218                         metatag = pd.DataFrame(bodies)
    219 
--> 220                         condition_results = seeqInterface.push_formula(metatag, self.workbook_id, self.worksheet_name)
    221                         self.condition_results = condition_results
    222                         return

~/.local/lib/python3.8/site-packages/seeq/addons/clustering/app/seeqInterface/main.py in push_formula(data, workbook_id, worksheet_name, quiet)
    208 	"""
    209 
--> 210 	results = spy.push(
    211                         metadata=data,
    212                         workbook = workbook_id,

/usr/local/lib/python3.8/site-packages/seeq/spy/_push.py in push(data, metadata, replace, workbook, worksheet, datasource, archive, type_mismatches, errors, quiet, status, session)
    298             else:
    299                 capsule_property_metadata = {k.lower(): v for k, v in metadata.pop('Capsule Property Units')[0].items()}
--> 300         push_result_df = _metadata.push(session, metadata, workbook_id, datasource_output, sync_token, errors,
    301                                         status.create_inner('Push Metadata'))  # type: pd.DataFrame
    302 

/usr/local/lib/python3.8/site-packages/seeq/spy/_metadata.py in push(session, metadata, workbook_id, datasource_output, sync_token, errors, status)
    128         _print_push_progress()
    129 
--> 130         _flush(session, put_signals_input, put_scalars_input, condition_batch_input, threshold_metric_inputs,
    131                asset_batch_input, tree_batch_input, push_results_df, errors)
    132 

/usr/local/lib/python3.8/site-packages/seeq/spy/_metadata.py in _flush(session, put_signals_input, put_scalars_input, condition_batch_input, threshold_metric_inputs, asset_batch_input, tree_batch_input, push_results_df, errors)
   1003 
   1004     if len(condition_batch_input.conditions) > 0:
-> 1005         _post_batch(session, lambda: conditions_api.put_conditions(body=condition_batch_input),
   1006                     condition_batch_input.conditions, errors, push_results_df, items_api)
   1007         condition_batch_input.conditions = list()

/usr/local/lib/python3.8/site-packages/seeq/spy/_metadata.py in _post_batch(session, post_function, item_inputs, errors, push_results_df, items_api)
    973 def _post_batch(session: Session, post_function, item_inputs, errors, push_results_df, items_api):
    974     item_batch_output = post_function()
--> 975     repost = _process_batch_output(session, item_inputs, item_batch_output.item_updates, errors, push_results_df,
    976                                    items_api)
    977     if repost:

/usr/local/lib/python3.8/site-packages/seeq/spy/_metadata.py in _process_batch_output(session, item_inputs, item_updates, errors, push_results_df, items_api)
    966 
    967         if hasattr(item_input, 'dataframe_index'):
--> 968             _set_push_result_string(item_input.dataframe_index, item_update_output, errors, push_results_df, items_api)
    969 
    970     return repost

/usr/local/lib/python3.8/site-packages/seeq/spy/_metadata.py in _set_push_result_string(dfi, iuo, errors, push_results_df, items_api)
    898         if iuo.error_message is not None:
    899             if errors == 'raise':
--> 900                 raise SPyRuntimeError('Error pushing "%s": %s' % (iuo.data_id, iuo.error_message))
    901             result_string = iuo.error_message
    902         else:

SPyRuntimeError: Error pushing "[019307A1-EB74-4CB7-8E76-706495E9F0A1] {Condition} Cluster 0 05/19/2022, 15:24:10": Failed to write item in batch request: Function 'ClusteringCalc_ndim' was not found or was archived at 'ClusteringCalc_ndim', line=1, column

**Comment by eparsonnet93** [comment] 2022-05-19 20:01
I was able to reproduce the error by attempting to push a formula to Seeq where the name of the formula does not match the name of any formula in Seeq. This likely in clustering occurred because of some issue during [steps 4-9 of the external calc installation](https://github.com/seeq12/seeq-clustering#installation), or perhaps the external calculation script was removed. 

Three questions to help diagnose:

1. What version of Seeq are you running?
2. Was this your first attempt at using the clustering tool or had it been working previously?
3. Are you able to see the 'ClusteringCalc_ndim' formula in Seeq workbook? *i.e.*, when you attempt to create a new formula in a seeq workbook (Tools>>Overview>>Formula) are you able to search and find 'ClusteringCalc_ndim'? It should [look something like this](https://github.com/seeq12/seeq-clustering/blob/main/images/formula.PNG)

**Comment by eparsonnet93** [comment] 2022-06-30 18:19
I have been made aware of an identical issue occurring after changes were made to the Seeq server (i.e. upgrading version). This is likely the case if clustering was, at one point, working, and then stopped working. The solution is as follows:

You will need to delete the `example` folder in the `Seeq/plugins/external-calculation/` directory. In order to do this, you will likely need need to shut down the Seeq server. After deleting the folder (with Seeq still shutdown), you will also need to reinstall hdbscan. Follow step 9 of [installation](https://github.com/seeq12/seeq-clustering#installation) to do so. You can then restart Seeq.

**Comment by eparsonnet93** [comment] 2022-07-11 15:43
Closing this, given the two solutions above. Please raise again if issues persist.

**Closed as completed by eparsonnet93** 2022-07-11 15:43 UTC
